apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: catalog-v2-firefox
spec:
  destination:
    name: catalog
  precedence: 2
  match:
    request:
      headers:
        user-agent:
          regex: ".*Firefox.*"
  route:
  - labels:
      version: v2
